//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EduTecEntities : DbContext
    {
        public EduTecEntities()
            : base("name=EduTecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumnoes { get; set; }
        public virtual DbSet<aud_curso_modif> aud_curso_modif { get; set; }
        public virtual DbSet<Ciclo> Cicloes { get; set; }
        public virtual DbSet<Curso> Cursoes { get; set; }
        public virtual DbSet<CursoProgramado> CursoProgramadoes { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Matricula> Matriculas { get; set; }
        public virtual DbSet<Parametro> Parametroes { get; set; }
        public virtual DbSet<Profesor> Profesors { get; set; }
        public virtual DbSet<Tarifa> Tarifas { get; set; }
    
        [DbFunction("EduTecEntities", "CursosDictadosDocente")]
        public virtual IQueryable<CursosDictadosDocente_Result> CursosDictadosDocente(string codigo, string ciclo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var cicloParameter = ciclo != null ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CursosDictadosDocente_Result>("[EduTecEntities].[CursosDictadosDocente](@codigo, @ciclo)", codigoParameter, cicloParameter);
        }
    
        public virtual int usp_registra_Curso(string idCurso, string idTarifa, string nomCurso)
        {
            var idCursoParameter = idCurso != null ?
                new ObjectParameter("IdCurso", idCurso) :
                new ObjectParameter("IdCurso", typeof(string));
    
            var idTarifaParameter = idTarifa != null ?
                new ObjectParameter("IdTarifa", idTarifa) :
                new ObjectParameter("IdTarifa", typeof(string));
    
            var nomCursoParameter = nomCurso != null ?
                new ObjectParameter("NomCurso", nomCurso) :
                new ObjectParameter("NomCurso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_registra_Curso", idCursoParameter, idTarifaParameter, nomCursoParameter);
        }
    
        public virtual ObjectResult<usp_reporte_CumplimientoCurso_Result> usp_reporte_CumplimientoCurso(string idCiclo)
        {
            var idCicloParameter = idCiclo != null ?
                new ObjectParameter("IdCiclo", idCiclo) :
                new ObjectParameter("IdCiclo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_reporte_CumplimientoCurso_Result>("usp_reporte_CumplimientoCurso", idCicloParameter);
        }
    
        public virtual ObjectResult<usp_reporte_HistorialAlumno_Result> usp_reporte_HistorialAlumno(string idCodigo)
        {
            var idCodigoParameter = idCodigo != null ?
                new ObjectParameter("IdCodigo", idCodigo) :
                new ObjectParameter("IdCodigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_reporte_HistorialAlumno_Result>("usp_reporte_HistorialAlumno", idCodigoParameter);
        }
    }
}
