//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aud_curso_modif
    {
        public int id { get; set; }
        public string cur_id { get; set; }
        public string observaciones { get; set; }
        public string valor_antes { get; set; }
        public string valor_despues { get; set; }
        public string usuario_bd { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
