//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoProgramado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CursoProgramado()
        {
            this.Matriculas = new HashSet<Matricula>();
        }
    
        public int IdCursoProg { get; set; }
        public string IdCurso { get; set; }
        public string IdCiclo { get; set; }
        public string IdProfesor { get; set; }
        public decimal Vacantes { get; set; }
        public decimal Matriculados { get; set; }
        public decimal PreCursoProg { get; set; }
        public string Horario { get; set; }
        public decimal Activo { get; set; }
    
        public virtual Ciclo Ciclo { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Profesor Profesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matricula> Matriculas { get; set; }
    }
}
