//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public string IdEmpleado { get; set; }
        public string Clave { get; set; }
        public string ApeEmpleado { get; set; }
        public string NomEmpleado { get; set; }
        public string Cargo { get; set; }
        public string DirEmpleado { get; set; }
        public string TelEmpleado { get; set; }
        public string EmailEmpleado { get; set; }
    }
}
