//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        public int IdCursoProg { get; set; }
        public string IdAlumno { get; set; }
        public System.DateTime FecMatricula { get; set; }
        public Nullable<decimal> ExaParcial { get; set; }
        public Nullable<decimal> ExaFinal { get; set; }
        public Nullable<decimal> Promedio { get; set; }
        public decimal Subsanacion { get; set; }
        public Nullable<decimal> ExaSub { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual CursoProgramado CursoProgramado { get; set; }
    }
}
