//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesor()
        {
            this.CursoProgramadoes = new HashSet<CursoProgramado>();
        }
    
        public string IdProfesor { get; set; }
        public string ApeProfesor { get; set; }
        public string NomProfesor { get; set; }
        public string DirProfesor { get; set; }
        public string TelProfesor { get; set; }
        public string EmailProfesor { get; set; }
        public string Clave { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursoProgramado> CursoProgramadoes { get; set; }
    }
}
